-- =============================================================================
-- Lead CRM partial export
-- Generated: 2026-07-13T07:56:54.456Z
-- Lead IDs: 914, 915, 916, 917, 918, 919, 920, 921, 922
--
-- Included leads:
--   #914  CityMall
--   #915  innovativeengg.co.in
--   #916  pawannirbhay.in
--   #917  wastelink.co
--   #918  KarPragati Technologies Pvt Ltd
--   #919  zenithratech.com
--   #920  BATCHMAN TECHNOLOGIES
--   #921  prashaktifinance.com
--   #922  Inknowtech
--
-- Import: psql -h HOST -p PORT -U USER -d DBNAME -f leads_914_922.sql
-- FK checks are deferred during import via session_replication_role = replica
-- =============================================================================
BEGIN;
SET session_replication_role = replica;

-- Users referenced by these leads (2 rows)
INSERT INTO users (user_id, name, email, password_hash, role, team_id, active, barcode, permissions, created_at, updated_at, status, user_type, approved_by, approved_at, rejection_reason, company_name, gst_number, mobile_no, last_login, last_login_ip, deactivated_at, deactivated_by, deactivation_reason, profile_photo_url, designation, department, employee_id, joining_date, notes) VALUES (31, 'Harshit', 'harshit@rentfoxxy.com', '$2a$10$.ZxHxOdybs1/iDOLhuclheqWHW45RXehTvwxwBty8H1hzLzODjwYu', 'sales', NULL, TRUE, NULL, '[]', '2026-06-26 05:41:07.956+00'::timestamptz, '2026-06-26 22:58:01.087+00'::timestamptz, 'active', 'internal', NULL, NULL, NULL, NULL, NULL, '9205940064', '2026-06-26 22:58:01.087+00'::timestamptz, '::ffff:127.0.0.1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, name, email, password_hash, role, team_id, active, barcode, permissions, created_at, updated_at, status, user_type, approved_by, approved_at, rejection_reason, company_name, gst_number, mobile_no, last_login, last_login_ip, deactivated_at, deactivated_by, deactivation_reason, profile_photo_url, designation, department, employee_id, joining_date, notes) VALUES (1, 'Super Admin', 'superadmin@rentfoxxy.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyO.TQkPsUdP6PdWCZjFVMCVrBZyDqKH/K', 'super_admin', NULL, TRUE, NULL, '[]', '2026-06-14 11:57:00.158+00'::timestamptz, '2026-07-11 12:09:16.383+00'::timestamptz, 'active', 'internal', NULL, NULL, NULL, NULL, NULL, '9900000001', '2026-07-11 12:09:16.383+00'::timestamptz, '::ffff:127.0.0.1', NULL, NULL, NULL, NULL, 'Super Administrator', NULL, NULL, NULL, NULL) ON CONFLICT (user_id) DO NOTHING;

-- leads (9 rows) — customer_id deferred to avoid circular FK
INSERT INTO leads (lead_id, name, company_name, email, phone, city, source, status, assigned_user_id, assigned_by, assigned_at, follow_up_date, is_duplicate, duplicate_of, rejection_reason, research_status, research_requested_at, created_at, updated_at, lead_stage, quotation_accept_token, quotation_accepted_at, quotation_last_sent_at, quotation_last_estimate_no, quotation_last_to_email, whatsapp_number, designation, quantity_required, monthly_budget, rental_duration, use_case, company_type, company_size, industry, annual_revenue, pan_number, gst_number, state, pincode, billing_address, shipping_same_as_billing, shipping_address, follow_up_time, converted_at, converted_by, customer_id, inquiry_type, last_activity_at, company_brand, brand, processor, generation, ram, storage, personal_remarks) VALUES (914, 'Harpreet', 'CityMall ', '', '8700169200', 'Gurgaon ', 'Email', 'Cold', NULL, 31, '2026-07-09 05:22:55.066+00'::timestamptz, '2026-07-14 00:00:00.000+00'::timestamptz, FALSE, NULL, NULL, 'completed', '2026-07-09 09:06:26.918+00'::timestamptz, '2026-07-09 05:22:55.066+00'::timestamptz, '2026-07-10 13:24:37.830+00'::timestamptz, 'Proposal Shared', NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, NULL, '', '', NULL, '', '', '', '', '', '', NULL, TRUE, NULL, '14:00:00'::time, NULL, NULL, NULL, 'rental', '2026-07-10 13:24:37.830+00'::timestamptz, ' ', 'Rentfoxxy', 'Intel Core i5', '11th Gen', '16 GB', '512 GB SSD', '') ON CONFLICT (lead_id) DO NOTHING;
INSERT INTO leads (lead_id, name, company_name, email, phone, city, source, status, assigned_user_id, assigned_by, assigned_at, follow_up_date, is_duplicate, duplicate_of, rejection_reason, research_status, research_requested_at, created_at, updated_at, lead_stage, quotation_accept_token, quotation_accepted_at, quotation_last_sent_at, quotation_last_estimate_no, quotation_last_to_email, whatsapp_number, designation, quantity_required, monthly_budget, rental_duration, use_case, company_type, company_size, industry, annual_revenue, pan_number, gst_number, state, pincode, billing_address, shipping_same_as_billing, shipping_address, follow_up_time, converted_at, converted_by, customer_id, inquiry_type, last_activity_at, company_brand, brand, processor, generation, ram, storage, personal_remarks) VALUES (915, 'V. Sathyamoorthi', 'innovativeengg.co.in', 'sathyamoorthi.v@innovativeengg.co.in', '9150033959', 'Coimbatore', 'Email', 'Cold', NULL, NULL, NULL, '2026-07-14 00:00:00.000+00'::timestamptz, FALSE, NULL, NULL, 'completed', '2026-07-09 12:00:35.164+00'::timestamptz, '2026-07-09 12:00:09.000+00'::timestamptz, '2026-07-13 05:40:34.354+00'::timestamptz, 'In Follow Up', NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, NULL, '', '', NULL, '', '', '', '', '', '', NULL, TRUE, NULL, '00:00:00'::time, NULL, NULL, NULL, 'rental', '2026-07-13 05:40:34.354+00'::timestamptz, '', '', 'Intel Core i5', '8th Gen', '8 GB', '256 GB SSD', 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: Corporate Rental Enquiry - Rentfoxxy (Ads)
Received At: 2026-07-09T12:00:09.000Z') ON CONFLICT (lead_id) DO NOTHING;
INSERT INTO leads (lead_id, name, company_name, email, phone, city, source, status, assigned_user_id, assigned_by, assigned_at, follow_up_date, is_duplicate, duplicate_of, rejection_reason, research_status, research_requested_at, created_at, updated_at, lead_stage, quotation_accept_token, quotation_accepted_at, quotation_last_sent_at, quotation_last_estimate_no, quotation_last_to_email, whatsapp_number, designation, quantity_required, monthly_budget, rental_duration, use_case, company_type, company_size, industry, annual_revenue, pan_number, gst_number, state, pincode, billing_address, shipping_same_as_billing, shipping_address, follow_up_time, converted_at, converted_by, customer_id, inquiry_type, last_activity_at, company_brand, brand, processor, generation, ram, storage, personal_remarks) VALUES (916, 'ARPITA SHARMA', 'pawannirbhay.in', 'director@pawannirbhay.in', '6395219195', 'delhi Received with following details', 'Email', 'Rejected', NULL, NULL, NULL, NULL, FALSE, NULL, 'Agreement Terms Not Match', 'completed', '2026-07-10 04:11:06.815+00'::timestamptz, '2026-07-10 04:10:51.000+00'::timestamptz, '2026-07-10 12:48:01.221+00'::timestamptz, 'Agreement Terms Not Match', NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, NULL, '', '', NULL, '', '', '', '07AAQCP1134P1ZX', '', '', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, 'rental', '2026-07-10 12:48:01.221+00'::timestamptz, '', 'Rentfoxxy', 'Intel Core i7', '13th Gen', '32 GB', '512 GB SSD', 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: Corporate Rental Enquiry - TIDADS2024
Received At: 2026-07-10T04:10:51.000Z') ON CONFLICT (lead_id) DO NOTHING;
INSERT INTO leads (lead_id, name, company_name, email, phone, city, source, status, assigned_user_id, assigned_by, assigned_at, follow_up_date, is_duplicate, duplicate_of, rejection_reason, research_status, research_requested_at, created_at, updated_at, lead_stage, quotation_accept_token, quotation_accepted_at, quotation_last_sent_at, quotation_last_estimate_no, quotation_last_to_email, whatsapp_number, designation, quantity_required, monthly_budget, rental_duration, use_case, company_type, company_size, industry, annual_revenue, pan_number, gst_number, state, pincode, billing_address, shipping_same_as_billing, shipping_address, follow_up_time, converted_at, converted_by, customer_id, inquiry_type, last_activity_at, company_brand, brand, processor, generation, ram, storage, personal_remarks) VALUES (917, 'Bharti Garg', 'wastelink.co', 'bharti.garg@wastelink.co', '7078530770', 'New Delhi', 'Email', 'Cold', NULL, NULL, NULL, '2026-07-13 00:00:00.000+00'::timestamptz, FALSE, NULL, NULL, 'completed', '2026-07-10 05:08:48.424+00'::timestamptz, '2026-07-10 05:08:10.000+00'::timestamptz, '2026-07-10 13:28:31.463+00'::timestamptz, 'Proposal Shared', NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, NULL, '', '', NULL, '', '', '', '', '', '', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, 'rental', '2026-07-10 13:28:31.463+00'::timestamptz, '', 'Rentfoxxy', 'Intel Core i5', '8th Gen', '8 GB', '256 GB SSD', 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026
Received At: 2026-07-10T05:08:14.000Z

Requirement Details:
Page Url: https://rentfoxxy.com Please review the enqui') ON CONFLICT (lead_id) DO NOTHING;
INSERT INTO leads (lead_id, name, company_name, email, phone, city, source, status, assigned_user_id, assigned_by, assigned_at, follow_up_date, is_duplicate, duplicate_of, rejection_reason, research_status, research_requested_at, created_at, updated_at, lead_stage, quotation_accept_token, quotation_accepted_at, quotation_last_sent_at, quotation_last_estimate_no, quotation_last_to_email, whatsapp_number, designation, quantity_required, monthly_budget, rental_duration, use_case, company_type, company_size, industry, annual_revenue, pan_number, gst_number, state, pincode, billing_address, shipping_same_as_billing, shipping_address, follow_up_time, converted_at, converted_by, customer_id, inquiry_type, last_activity_at, company_brand, brand, processor, generation, ram, storage, personal_remarks) VALUES (918, 'SUMIT JUYAL', 'KarPragati Technologies Pvt Ltd', 'sumit.juyal@karpragati.com', '7895766615', '', 'Other', 'Cold', NULL, 31, '2026-07-10 12:51:30.721+00'::timestamptz, '2026-07-14 00:00:00.000+00'::timestamptz, FALSE, NULL, NULL, 'completed', '2026-07-10 12:51:31.090+00'::timestamptz, '2026-07-10 12:51:30.721+00'::timestamptz, '2026-07-13 05:37:26.135+00'::timestamptz, 'Proposal Shared', NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, NULL, '', '', NULL, '', '', '', '', '', '', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, 'rental', '2026-07-13 05:37:26.135+00'::timestamptz, '', 'Rentfoxxy', 'Intel Core i7', '13th Gen', '32 GB', '512 GB SSD', '') ON CONFLICT (lead_id) DO NOTHING;
INSERT INTO leads (lead_id, name, company_name, email, phone, city, source, status, assigned_user_id, assigned_by, assigned_at, follow_up_date, is_duplicate, duplicate_of, rejection_reason, research_status, research_requested_at, created_at, updated_at, lead_stage, quotation_accept_token, quotation_accepted_at, quotation_last_sent_at, quotation_last_estimate_no, quotation_last_to_email, whatsapp_number, designation, quantity_required, monthly_budget, rental_duration, use_case, company_type, company_size, industry, annual_revenue, pan_number, gst_number, state, pincode, billing_address, shipping_same_as_billing, shipping_address, follow_up_time, converted_at, converted_by, customer_id, inquiry_type, last_activity_at, company_brand, brand, processor, generation, ram, storage, personal_remarks) VALUES (919, 'Kaustubh Bhargava', 'zenithratech.com', 'kaustabhbhargava@zenithratech.com', '9691740644', 'Gurgaon', 'Email', 'Cold', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, 'completed', '2026-07-11 12:28:16.909+00'::timestamptz, '2026-07-11 12:27:57.000+00'::timestamptz, '2026-07-13 05:35:33.611+00'::timestamptz, 'In Follow Up', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, NULL, NULL, NULL, NULL, NULL, 'rental', '2026-07-13 05:35:33.611+00'::timestamptz, NULL, NULL, NULL, NULL, NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Enquiry Submitted on Rentfoxxy Website!
Received At: 2026-07-11T12:28:00.000Z

Requirement Details:
Product Name: Gaming Laptop on rent with Graphic Card - Intel Core i5, 8GB') ON CONFLICT (lead_id) DO NOTHING;
INSERT INTO leads (lead_id, name, company_name, email, phone, city, source, status, assigned_user_id, assigned_by, assigned_at, follow_up_date, is_duplicate, duplicate_of, rejection_reason, research_status, research_requested_at, created_at, updated_at, lead_stage, quotation_accept_token, quotation_accepted_at, quotation_last_sent_at, quotation_last_estimate_no, quotation_last_to_email, whatsapp_number, designation, quantity_required, monthly_budget, rental_duration, use_case, company_type, company_size, industry, annual_revenue, pan_number, gst_number, state, pincode, billing_address, shipping_same_as_billing, shipping_address, follow_up_time, converted_at, converted_by, customer_id, inquiry_type, last_activity_at, company_brand, brand, processor, generation, ram, storage, personal_remarks) VALUES (920, 'RK NAIDU', 'BATCHMAN TECHNOLOGIES', 'batchmantechnologies@gmail.com', '7386558419', 'Visakhapatnam ', 'Other', 'Deal', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, 'completed', '2026-07-11 13:24:59.082+00'::timestamptz, '2026-07-11 13:24:58.741+00'::timestamptz, '2026-07-11 13:26:45.680+00'::timestamptz, 'Deal', NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, NULL, '', 'Pvt Ltd', NULL, '', '', '', '37EUOPK3206G1ZJ', 'Andhra Pradesh', '530016', NULL, TRUE, NULL, NULL, '2026-07-11 13:26:45.675+00'::timestamptz, 1, NULL, 'sales', '2026-07-11 13:26:45.680+00'::timestamptz, 'BATCHMAN TECHNOLOGIES', '', '', '', '', '', '') ON CONFLICT (lead_id) DO NOTHING;
INSERT INTO leads (lead_id, name, company_name, email, phone, city, source, status, assigned_user_id, assigned_by, assigned_at, follow_up_date, is_duplicate, duplicate_of, rejection_reason, research_status, research_requested_at, created_at, updated_at, lead_stage, quotation_accept_token, quotation_accepted_at, quotation_last_sent_at, quotation_last_estimate_no, quotation_last_to_email, whatsapp_number, designation, quantity_required, monthly_budget, rental_duration, use_case, company_type, company_size, industry, annual_revenue, pan_number, gst_number, state, pincode, billing_address, shipping_same_as_billing, shipping_address, follow_up_time, converted_at, converted_by, customer_id, inquiry_type, last_activity_at, company_brand, brand, processor, generation, ram, storage, personal_remarks) VALUES (921, 'Praveen Kumar', 'prashaktifinance.com', 'praveen.kumar@prashaktifinance.com', '9315879124', 'Gurugram Received with following details', 'Email', 'Cold', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, 'completed', '2026-07-13 04:47:13.120+00'::timestamptz, '2026-07-13 04:46:40.000+00'::timestamptz, '2026-07-13 05:03:45.113+00'::timestamptz, 'Proposal Shared', NULL, NULL, NULL, NULL, NULL, '', '', 12, NULL, NULL, '', '', NULL, '', '', '', '', '', '', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, 'rental', '2026-07-13 05:03:45.113+00'::timestamptz, '', '', 'Intel Core i5', '8th Gen', '8 GB', '256 GB SSD', 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: Corporate Rental Enquiry - TIDADS2024
Received At: 2026-07-13T04:46:40.000Z') ON CONFLICT (lead_id) DO NOTHING;
INSERT INTO leads (lead_id, name, company_name, email, phone, city, source, status, assigned_user_id, assigned_by, assigned_at, follow_up_date, is_duplicate, duplicate_of, rejection_reason, research_status, research_requested_at, created_at, updated_at, lead_stage, quotation_accept_token, quotation_accepted_at, quotation_last_sent_at, quotation_last_estimate_no, quotation_last_to_email, whatsapp_number, designation, quantity_required, monthly_budget, rental_duration, use_case, company_type, company_size, industry, annual_revenue, pan_number, gst_number, state, pincode, billing_address, shipping_same_as_billing, shipping_address, follow_up_time, converted_at, converted_by, customer_id, inquiry_type, last_activity_at, company_brand, brand, processor, generation, ram, storage, personal_remarks) VALUES (922, 'Manjunatha', 'Inknowtech ', 'manjunatha.kv@inknowtech.com', '9845575269', 'Mumbai ', 'Walk-in', 'Cold', NULL, 31, '2026-07-13 06:12:10.596+00'::timestamptz, NULL, FALSE, NULL, NULL, 'completed', '2026-07-13 07:08:07.520+00'::timestamptz, '2026-07-13 06:12:10.596+00'::timestamptz, '2026-07-13 07:08:07.590+00'::timestamptz, 'Proposal Shared', NULL, NULL, NULL, NULL, NULL, '', '', 1, NULL, NULL, '', '', NULL, '', '', '', '', 'Maharashtra', '', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, 'rental', '2026-07-13 07:08:07.590+00'::timestamptz, '', 'Lenovo', 'Intel Core i7', '10th Gen', '16 GB', '512 GB SSD', '') ON CONFLICT (lead_id) DO NOTHING;

-- lead_activities (81 rows)
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4088, 914, 31, 'profile_updated', NULL, NULL, 'Updated: company brand, city', '2026-07-09 05:23:41.172+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4084, 914, 31, 'lead_created', NULL, NULL, 'Lead created', '2026-07-09 05:22:55.097+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4113, 915, 31, 'follow_up_set', NULL, NULL, 'Monday morning ', '2026-07-10 05:34:24.688+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4085, 914, 31, 'profile_updated', NULL, NULL, 'Updated: company, company brand, city, assignee', '2026-07-09 05:22:55.189+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4086, 914, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-09 05:23:40.840+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4087, 914, 31, 'research_refreshed', NULL, NULL, 'Research auto-refreshed after company and company brand update', '2026-07-09 05:23:41.113+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4089, 914, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-09 05:24:08.897+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4090, 914, 31, 'research_refreshed', NULL, NULL, 'Research auto-refreshed after company brand update', '2026-07-09 05:24:09.121+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4091, 914, 31, 'profile_updated', NULL, NULL, 'Updated: company brand, city', '2026-07-09 05:24:09.176+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4092, 914, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-09 05:24:24.060+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4093, 914, 31, 'research_refreshed', NULL, NULL, 'Research auto-refreshed after company and company brand update', '2026-07-09 05:24:24.302+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4094, 914, 31, 'profile_updated', NULL, NULL, 'Updated: company brand, city', '2026-07-09 05:24:24.359+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4095, 914, 31, 'status_updated', 'Pending', 'Cold', 'Status updated to Cold / Proposal Shared via quick update', '2026-07-09 05:24:38.222+00'::timestamptz, NULL, 'Proposal Shared') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4096, 914, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-09 09:06:26.499+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4097, 914, 31, 'research_refreshed', NULL, NULL, 'Research auto-refreshed after company brand update', '2026-07-09 09:06:26.920+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4098, 914, 31, 'profile_updated', NULL, NULL, 'Updated: company brand, city, brand, processor, generation, ram, storage', '2026-07-09 09:06:26.999+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4099, 915, NULL, 'email_imported', NULL, 'Pending', 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: Corporate Rental Enquiry - Rentfoxxy (Ads)
Received At: 2026-07-09T12:00:09.000Z', '2026-07-09 12:00:33.324+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4100, 915, 31, 'status_updated', 'Pending', 'Cold', 'Status updated to Cold / In Follow Up via quick update', '2026-07-09 12:03:43.059+00'::timestamptz, NULL, 'In Follow Up') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4101, 916, NULL, 'email_imported', NULL, 'Pending', 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: Corporate Rental Enquiry - TIDADS2024
Received At: 2026-07-10T04:10:51.000Z', '2026-07-10 04:11:05.970+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4102, 916, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-10 05:04:44.860+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4103, 916, 31, 'profile_updated', NULL, NULL, 'Updated: brand, processor, generation, ram, storage', '2026-07-10 05:04:44.922+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4104, 917, NULL, 'email_imported', NULL, 'Pending', 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026
Received At: 2026-07-10T05:08:10.000Z

Requirement Details:
Page Url: https://rentfoxxy.com Please review the enqui', '2026-07-10 05:08:48.064+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4105, 917, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026
Received At: 2026-07-10T05:08:11.000Z

Requirement Details:
Page Url: https://rentfoxxy.com Please review the enqui', '2026-07-10 05:08:48.093+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4106, 917, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026
Received At: 2026-07-10T05:08:11.000Z

Requirement Details:
Page Url: https://rentfoxxy.com Please review the enqui', '2026-07-10 05:08:48.125+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4107, 917, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026
Received At: 2026-07-10T05:08:12.000Z

Requirement Details:
Page Url: https://rentfoxxy.com Please review the enqui', '2026-07-10 05:08:48.146+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4108, 917, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026
Received At: 2026-07-10T05:08:13.000Z

Requirement Details:
Page Url: https://rentfoxxy.com Please review the enqui', '2026-07-10 05:08:48.163+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4109, 917, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026
Received At: 2026-07-10T05:08:13.000Z

Requirement Details:
Page Url: https://rentfoxxy.com Please review the enqui', '2026-07-10 05:08:48.182+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4110, 917, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026
Received At: 2026-07-10T05:08:14.000Z

Requirement Details:
Page Url: https://rentfoxxy.com Please review the enqui', '2026-07-10 05:08:48.200+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4111, 916, 31, 'status_updated', 'Pending', 'Cold', 'Status updated to Cold / Proposal Shared via quick update', '2026-07-10 05:24:35.295+00'::timestamptz, NULL, 'Proposal Shared') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4112, 917, 31, 'status_updated', 'Pending', 'Cold', 'Status updated to Cold / Proposal Shared via quick update', '2026-07-10 05:24:54.881+00'::timestamptz, NULL, 'Proposal Shared') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4114, 914, 31, 'follow_up_set', NULL, NULL, 'Call back in afternoon ', '2026-07-10 05:34:55.279+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4115, 917, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-10 05:42:02.418+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4116, 917, 31, 'profile_updated', NULL, NULL, 'Updated: brand, processor, generation, ram, storage', '2026-07-10 05:42:02.591+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4117, 916, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-10 11:51:44.661+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4118, 916, 31, 'profile_updated', NULL, NULL, 'Updated: GST', '2026-07-10 11:51:44.735+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4119, 916, 31, 'status_updated', 'Cold', 'Deal', 'deal', '2026-07-10 11:51:54.368+00'::timestamptz, 'Proposal Shared', 'Deal') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4120, 916, 31, 'status_updated', 'Deal', 'Rejected', 'Status updated to Rejected / Agreement Terms Not Match via quick update', '2026-07-10 12:48:01.220+00'::timestamptz, 'Deal', 'Agreement Terms Not Match') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4121, 918, 31, 'lead_created', NULL, NULL, 'Lead created', '2026-07-10 12:51:30.734+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4122, 918, 31, 'profile_updated', NULL, NULL, 'Updated: assignee', '2026-07-10 12:51:30.828+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4123, 918, 31, 'status_updated', 'Pending', 'Cold', 'Status updated to Cold / Proposal Shared via quick update', '2026-07-10 12:51:39.631+00'::timestamptz, NULL, 'Proposal Shared') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4124, 918, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-10 12:52:40.695+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4125, 918, 31, 'profile_updated', NULL, NULL, 'Updated: brand, processor, generation, ram, storage', '2026-07-10 12:52:40.761+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4126, 914, 31, 'follow_up_set', NULL, NULL, 'Follow-up scheduled for 2026-07-14 at 14:00:00', '2026-07-10 13:24:37.830+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4127, 918, 31, 'follow_up_set', NULL, NULL, 'Follow-up scheduled for 2026-07-13', '2026-07-10 13:26:13.046+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4128, 917, 31, 'follow_up_set', NULL, NULL, 'Follow-up scheduled for 2026-07-13', '2026-07-10 13:28:31.463+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4129, 919, NULL, 'email_imported', NULL, 'Pending', 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Enquiry Submitted on Rentfoxxy Website!
Received At: 2026-07-11T12:27:57.000Z

Requirement Details:
Product Name: Gaming Laptop on rent with Graphic Card - Intel Core i5, 8GB', '2026-07-11 12:28:16.303+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4130, 919, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Enquiry Submitted on Rentfoxxy Website!
Received At: 2026-07-11T12:27:57.000Z

Requirement Details:
Product Name: Gaming Laptop on rent with Graphic Card - Intel Core i5, 8GB', '2026-07-11 12:28:16.333+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4131, 919, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Enquiry Submitted on Rentfoxxy Website!
Received At: 2026-07-11T12:27:58.000Z

Requirement Details:
Product Name: Gaming Laptop on rent with Graphic Card - Intel Core i5, 8GB', '2026-07-11 12:28:16.354+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4132, 919, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Enquiry Submitted on Rentfoxxy Website!
Received At: 2026-07-11T12:27:58.000Z

Requirement Details:
Product Name: Gaming Laptop on rent with Graphic Card - Intel Core i5, 8GB', '2026-07-11 12:28:16.383+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4133, 919, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Enquiry Submitted on Rentfoxxy Website!
Received At: 2026-07-11T12:27:59.000Z

Requirement Details:
Product Name: Gaming Laptop on rent with Graphic Card - Intel Core i5, 8GB', '2026-07-11 12:28:16.407+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4134, 919, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Enquiry Submitted on Rentfoxxy Website!
Received At: 2026-07-11T12:28:00.000Z

Requirement Details:
Product Name: Gaming Laptop on rent with Graphic Card - Intel Core i5, 8GB', '2026-07-11 12:28:16.456+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4135, 919, NULL, 'email_reingested', NULL, NULL, 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: New Enquiry Submitted on Rentfoxxy Website!
Received At: 2026-07-11T12:28:00.000Z

Requirement Details:
Product Name: Gaming Laptop on rent with Graphic Card - Intel Core i5, 8GB', '2026-07-11 12:28:16.477+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4136, 920, 1, 'lead_created', NULL, NULL, 'Lead created', '2026-07-11 13:24:58.754+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4137, 920, 1, 'profile_updated', NULL, NULL, 'Updated: name, company type, state, pincode, city, inquiry type', '2026-07-11 13:24:58.828+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4138, 920, 1, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-11 13:25:33.918+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4139, 920, 1, 'profile_updated', NULL, NULL, 'Updated: city', '2026-07-11 13:25:33.984+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4140, 920, 1, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-11 13:25:53.293+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4141, 920, 1, 'profile_updated', NULL, NULL, 'Updated: GST, city', '2026-07-11 13:25:53.365+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4142, 920, 1, 'status_updated', 'Pending', 'Deal', 'Deal', '2026-07-11 13:26:01.725+00'::timestamptz, NULL, 'Deal') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4143, 920, 1, 'converted_to_customer', NULL, NULL, 'Converted to customer #292', '2026-07-11 13:26:45.679+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4144, 921, NULL, 'email_imported', NULL, 'Pending', 'Lead imported from enquiry email.
Source Email: leads@rentfoxxy.com
Subject: Corporate Rental Enquiry - TIDADS2024
Received At: 2026-07-13T04:46:40.000Z', '2026-07-13 04:47:11.195+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4145, 921, 31, 'status_updated', 'Pending', 'Cold', 'Gurgaon , 12 laptop , 20 employee, industry - Finance quote shared

', '2026-07-13 05:01:04.987+00'::timestamptz, NULL, 'Proposal Shared') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4146, 921, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-13 05:03:36.546+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4147, 921, 31, 'profile_updated', NULL, NULL, 'Updated: quantity, processor, generation, ram, storage', '2026-07-13 05:03:36.609+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4148, 921, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-13 05:03:45.053+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4149, 921, 31, 'profile_updated', NULL, NULL, 'Profile updated', '2026-07-13 05:03:45.113+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4152, 919, 31, 'status_updated', 'Pending', 'Cold', 'Status updated to Cold / In Follow Up via quick update', '2026-07-13 05:35:33.609+00'::timestamptz, NULL, 'In Follow Up') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4153, 918, 31, 'follow_up_set', NULL, NULL, 'Follow-up scheduled for 2026-07-14', '2026-07-13 05:37:26.134+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4154, 915, 31, 'follow_up_set', NULL, NULL, 'Follow-up scheduled for 2026-07-14 at 00:00:00', '2026-07-13 05:39:42.690+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4155, 915, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-13 05:40:34.288+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4156, 915, 31, 'profile_updated', NULL, NULL, 'Updated: processor, generation, ram, storage', '2026-07-13 05:40:34.354+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4157, 922, 31, 'lead_created', NULL, NULL, 'Lead created', '2026-07-13 06:12:10.613+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4158, 922, 31, 'profile_updated', NULL, NULL, 'Updated: state, city, assignee', '2026-07-13 06:12:10.687+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4159, 922, 31, 'status_updated', 'Pending', 'Cold', 'Status updated to Cold / Proposal Shared via quick update', '2026-07-13 06:12:20.068+00'::timestamptz, NULL, 'Proposal Shared') ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4160, 922, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-13 06:16:31.577+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4161, 922, 31, 'profile_updated', NULL, NULL, 'Updated: city', '2026-07-13 06:16:31.661+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4162, 922, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-13 06:18:59.170+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4163, 922, 31, 'profile_updated', NULL, NULL, 'Updated: quantity, city, brand, processor, generation, ram, storage', '2026-07-13 06:18:59.234+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4164, 922, 31, 'lead_basic_updated', NULL, NULL, 'Admin updated lead basic details', '2026-07-13 07:08:07.237+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4165, 922, 31, 'research_refreshed', NULL, NULL, 'Research auto-refreshed after company update', '2026-07-13 07:08:07.523+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO lead_activities (activity_id, lead_id, user_id, action, status_from, status_to, notes, created_at, stage_from, stage_to) VALUES (4166, 922, 31, 'profile_updated', NULL, NULL, 'Updated: city', '2026-07-13 07:08:07.590+00'::timestamptz, NULL, NULL) ON CONFLICT (activity_id) DO NOTHING;

-- lead_remarks (23 rows)
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1981, 914, 31, 'He needs i7/i5 quote shared will reach him out over call again as tried not responding', '2026-07-09 05:25:17.539+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1982, 914, 31, 'revised Quote shared price given 1850+tax final he will start from 10 - 15 laptops with time increase on rental right now 400 laptops', '2026-07-09 09:07:53.682+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1987, 914, 31, 'Had a discussion he will connect in lunch timing today will call back', '2026-07-10 05:33:27.017+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1992, 914, 31, 'Had a discussion meeting set for tuesday', '2026-07-10 13:25:06.846+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1983, 915, 31, '10 years old 120 employee industry - car door manufacturing tata, Mahindra, need 6 laptops', '2026-07-09 12:07:26.036+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1984, 915, 31, 'Looking for new laptop informed refurb we deal he will be sharing quote by tomorrow hence mail dropped for requirements', '2026-07-09 12:08:29.004+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1988, 915, 31, 'MD on leave asked to connect on monday', '2026-07-10 05:34:02.609+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1985, 916, 31, 'E- commerce industry 100+employee 1 laptop needed. Quote shared needed for programing', '2026-07-10 05:05:28.592+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1989, 916, 31, 'Had a discussion have budget constrains pitched i5 11gen 16/512 2100+Tax she will get back', '2026-07-10 05:39:00.710+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1991, 916, 31, 'Company issue there funds are suspicious as informed by accounts so we are not proceeding further', '2026-07-10 12:50:10.203+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1986, 917, 31, 'quote shared need 150 units Delhi based company want to change vendor quality issue', '2026-07-10 05:27:35.589+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1990, 917, 31, 'She will reach office and update for the same', '2026-07-10 05:43:09.358+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1994, 917, 31, 'Called not responding will connect back', '2026-07-10 13:28:26.097+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1995, 917, 31, 'Had a discussion she was busy whole day she will check quote and connect back', '2026-07-10 13:29:58.153+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (2000, 917, 31, 'pinned on mail for update as not responding over call hanging up', '2026-07-13 05:39:11.064+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (2001, 917, 31, 'She asked to connect at 3 pm', '2026-07-13 05:56:37.020+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1993, 918, 31, 'Quote shared he mentioned need time for final verdict', '2026-07-10 13:26:37.010+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1997, 918, 31, 'He is forwarding this to management will get back', '2026-07-13 05:23:30.634+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1999, 919, 31, 'Called no response pinned on whatsapp', '2026-07-13 05:35:49.931+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1996, 921, 31, 'Gurgaon , 12 laptop , 20 employee, industry - Finance quote shared', '2026-07-13 05:00:01.462+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (1998, 921, 31, 'Had a discussion older vendor offering at 650 informed its i5 he is using i3 he said will get back', '2026-07-13 05:25:42.267+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (2002, 922, 31, 'Quote shared old customer', '2026-07-13 06:15:43.344+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;
INSERT INTO lead_remarks (remark_id, lead_id, user_id, note, created_at) VALUES (2003, 922, 31, 'Quote shared he need lenovo thinkpad', '2026-07-13 06:18:34.723+00'::timestamptz) ON CONFLICT (remark_id) DO NOTHING;

-- lead_assignments (3 rows)
INSERT INTO lead_assignments (assignment_id, lead_id, assigned_to, assigned_by, assigned_at, batch_id) VALUES (1154, 914, 31, 31, '2026-07-09 05:22:55.066+00'::timestamptz, NULL) ON CONFLICT (assignment_id) DO NOTHING;
INSERT INTO lead_assignments (assignment_id, lead_id, assigned_to, assigned_by, assigned_at, batch_id) VALUES (1155, 918, 31, 31, '2026-07-10 12:51:30.721+00'::timestamptz, NULL) ON CONFLICT (assignment_id) DO NOTHING;
INSERT INTO lead_assignments (assignment_id, lead_id, assigned_to, assigned_by, assigned_at, batch_id) VALUES (1156, 922, 31, 31, '2026-07-13 06:12:10.596+00'::timestamptz, NULL) ON CONFLICT (assignment_id) DO NOTHING;

-- lead_company_research (9 rows)
INSERT INTO lead_company_research (research_id, lead_id, cin, entity_type, roc, revenue, employees, gst, address, city, state, raw_response, researched_at, industry, pincode) VALUES (1467, 914, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', '{"cin":"Unknown","gst":"Unknown","roc":"Unknown","city":"Unknown","state":"Unknown","address":"Unknown","pincode":"Unknown","revenue":"Unknown","summary":"Research unavailable for \"CityMall\". Add details manually.","website":"","industry":"Unknown","employees":"Unknown","departments":[],"entity_type":"Unknown","twitter_url":"","facebook_url":"","linkedin_url":"","technologies":[],"subsidiary_of":"Unknown","total_funding":"Unknown","annual_revenue":"Unknown","latest_funding":"Unknown","latest_funding_amount":"Unknown"}'::jsonb, '2026-07-09 05:22:55.482+00'::timestamptz, 'Unknown', 'Unknown') ON CONFLICT (research_id) DO NOTHING;
INSERT INTO lead_company_research (research_id, lead_id, cin, entity_type, roc, revenue, employees, gst, address, city, state, raw_response, researched_at, industry, pincode) VALUES (1472, 915, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', '{"cin":"Unknown","gst":"Unknown","roc":"Unknown","city":"Unknown","state":"Unknown","address":"Unknown","pincode":"Unknown","revenue":"Unknown","summary":"Research unavailable for \"innovativeengg.co.in\". Add details manually.","website":"","industry":"Unknown","employees":"Unknown","departments":[],"entity_type":"Unknown","twitter_url":"","facebook_url":"","linkedin_url":"","technologies":[],"subsidiary_of":"Unknown","total_funding":"Unknown","annual_revenue":"Unknown","latest_funding":"Unknown","latest_funding_amount":"Unknown"}'::jsonb, '2026-07-09 12:00:35.147+00'::timestamptz, 'Unknown', 'Unknown') ON CONFLICT (research_id) DO NOTHING;
INSERT INTO lead_company_research (research_id, lead_id, cin, entity_type, roc, revenue, employees, gst, address, city, state, raw_response, researched_at, industry, pincode) VALUES (1473, 916, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', '07AAQCP1134P1ZX', 'Unknown', 'Unknown', 'Unknown', '{"cin":"Unknown","gst":"Unknown","roc":"Unknown","city":"Unknown","state":"Unknown","address":"Unknown","pincode":"Unknown","revenue":"Unknown","summary":"Research unavailable for \"pawannirbhay.in\". Add details manually.","website":"","industry":"Unknown","employees":"Unknown","departments":[],"entity_type":"Unknown","twitter_url":"","facebook_url":"","linkedin_url":"","technologies":[],"subsidiary_of":"Unknown","total_funding":"Unknown","annual_revenue":"Unknown","latest_funding":"Unknown","latest_funding_amount":"Unknown"}'::jsonb, '2026-07-10 04:11:06.795+00'::timestamptz, 'Unknown', 'Unknown') ON CONFLICT (research_id) DO NOTHING;
INSERT INTO lead_company_research (research_id, lead_id, cin, entity_type, roc, revenue, employees, gst, address, city, state, raw_response, researched_at, industry, pincode) VALUES (1474, 917, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', '{"cin":"Unknown","gst":"Unknown","roc":"Unknown","city":"Unknown","state":"Unknown","address":"Unknown","pincode":"Unknown","revenue":"Unknown","summary":"Research unavailable for \"wastelink.co\". Add details manually.","website":"","industry":"Unknown","employees":"Unknown","departments":[],"entity_type":"Unknown","twitter_url":"","facebook_url":"","linkedin_url":"","technologies":[],"subsidiary_of":"Unknown","total_funding":"Unknown","annual_revenue":"Unknown","latest_funding":"Unknown","latest_funding_amount":"Unknown"}'::jsonb, '2026-07-10 05:08:48.351+00'::timestamptz, 'Unknown', 'Unknown') ON CONFLICT (research_id) DO NOTHING;
INSERT INTO lead_company_research (research_id, lead_id, cin, entity_type, roc, revenue, employees, gst, address, city, state, raw_response, researched_at, industry, pincode) VALUES (1482, 918, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', '{"cin":"Unknown","gst":"Unknown","roc":"Unknown","city":"Unknown","state":"Unknown","address":"Unknown","pincode":"Unknown","revenue":"Unknown","summary":"Research unavailable for \"KarPragati Technologies Pvt Ltd\". Add details manually.","website":"","industry":"Unknown","employees":"Unknown","departments":[],"entity_type":"Unknown","twitter_url":"","facebook_url":"","linkedin_url":"","technologies":[],"subsidiary_of":"Unknown","total_funding":"Unknown","annual_revenue":"Unknown","latest_funding":"Unknown","latest_funding_amount":"Unknown"}'::jsonb, '2026-07-10 12:51:31.079+00'::timestamptz, 'Unknown', 'Unknown') ON CONFLICT (research_id) DO NOTHING;
INSERT INTO lead_company_research (research_id, lead_id, cin, entity_type, roc, revenue, employees, gst, address, city, state, raw_response, researched_at, industry, pincode) VALUES (1484, 919, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', '{"cin":"Unknown","gst":"Unknown","roc":"Unknown","city":"Unknown","state":"Unknown","address":"Unknown","pincode":"Unknown","revenue":"Unknown","summary":"Research unavailable for \"zenithratech.com\". Add details manually.","website":"","industry":"Unknown","employees":"Unknown","departments":[],"entity_type":"Unknown","twitter_url":"","facebook_url":"","linkedin_url":"","technologies":[],"subsidiary_of":"Unknown","total_funding":"Unknown","annual_revenue":"Unknown","latest_funding":"Unknown","latest_funding_amount":"Unknown"}'::jsonb, '2026-07-11 12:28:16.874+00'::timestamptz, 'Unknown', 'Unknown') ON CONFLICT (research_id) DO NOTHING;
INSERT INTO lead_company_research (research_id, lead_id, cin, entity_type, roc, revenue, employees, gst, address, city, state, raw_response, researched_at, industry, pincode) VALUES (1490, 920, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', '37EUOPK3206G1ZJ', 'Unknown', 'Unknown', 'Unknown', '{"cin":"Unknown","gst":"Unknown","roc":"Unknown","city":"Unknown","state":"Unknown","address":"Unknown","pincode":"Unknown","revenue":"Unknown","summary":"Research unavailable for \"BATCHMAN TECHNOLOGIES\". Add details manually.","website":"","industry":"Unknown","employees":"Unknown","departments":[],"entity_type":"Unknown","twitter_url":"","facebook_url":"","linkedin_url":"","technologies":[],"subsidiary_of":"Unknown","total_funding":"Unknown","annual_revenue":"Unknown","latest_funding":"Unknown","latest_funding_amount":"Unknown"}'::jsonb, '2026-07-11 13:24:59.076+00'::timestamptz, 'Unknown', 'Unknown') ON CONFLICT (research_id) DO NOTHING;
INSERT INTO lead_company_research (research_id, lead_id, cin, entity_type, roc, revenue, employees, gst, address, city, state, raw_response, researched_at, industry, pincode) VALUES (1492, 921, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', '{"cin":"Unknown","gst":"Unknown","roc":"Unknown","city":"Unknown","state":"Unknown","address":"Unknown","pincode":"Unknown","revenue":"Unknown","summary":"Research unavailable for \"prashaktifinance.com\". Add details manually.","website":"","industry":"Unknown","employees":"Unknown","departments":[],"entity_type":"Unknown","twitter_url":"","facebook_url":"","linkedin_url":"","technologies":[],"subsidiary_of":"Unknown","total_funding":"Unknown","annual_revenue":"Unknown","latest_funding":"Unknown","latest_funding_amount":"Unknown"}'::jsonb, '2026-07-13 04:47:13.104+00'::timestamptz, 'Unknown', 'Unknown') ON CONFLICT (research_id) DO NOTHING;
INSERT INTO lead_company_research (research_id, lead_id, cin, entity_type, roc, revenue, employees, gst, address, city, state, raw_response, researched_at, industry, pincode) VALUES (1493, 922, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', '{"cin":"Unknown","gst":"Unknown","roc":"Unknown","city":"Unknown","state":"Unknown","address":"Unknown","pincode":"Unknown","revenue":"Unknown","summary":"Research unavailable for \"Inknowtech Lenovo\". Add details manually.","website":"","industry":"Unknown","employees":"Unknown","departments":[],"entity_type":"Unknown","twitter_url":"","facebook_url":"","linkedin_url":"","technologies":[],"subsidiary_of":"Unknown","total_funding":"Unknown","annual_revenue":"Unknown","latest_funding":"Unknown","latest_funding_amount":"Unknown"}'::jsonb, '2026-07-13 06:12:10.979+00'::timestamptz, 'Unknown', 'Unknown') ON CONFLICT (research_id) DO NOTHING;

-- email_lead_ingestion_log (17 rows)
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (614, '<Shk3DLx7yiX9IOb6jUAC0YJ9BNmYlIgO6p2IUoenFE@rental.rentfoxxy.com>', '[Gmail]/Sent Mail', 'Corporate Rental Enquiry - Rentfoxxy (Ads)', 915, '2026-07-09 12:00:33.330+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (616, '<BibozFAK0NFEu99t2Fak8I9TfyzZZoFtxuzURXPezA@rental.truetechservices.in>', '[Gmail]/Sent Mail', 'Corporate Rental Enquiry - TIDADS2024', 916, '2026-07-10 04:11:06.040+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (618, '<c81a9c1659146d36d944c36abf764055@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026', 917, '2026-07-10 05:08:48.068+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (619, '<b0eacac51bb3c3edf4cdf8ded30b9683@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026', 917, '2026-07-10 05:08:48.095+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (620, '<0474d036313327855fef72dbc3e9fbaa@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026', 917, '2026-07-10 05:08:48.127+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (621, '<2d3170a32187a9a372ca200d3f7299a5@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026', 917, '2026-07-10 05:08:48.147+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (622, '<c191c547cba44737945fb61572679376@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026', 917, '2026-07-10 05:08:48.165+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (623, '<7a4f19f16d25aef3325096f10cb4a084@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026', 917, '2026-07-10 05:08:48.183+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (624, '<73e387f612a1b8919e6d70f44c4335ef@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Popup Enquiry Submitted on Rentfoxxy Website - 10 Jul 2026', 917, '2026-07-10 05:08:48.201+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (626, '<9d705d14af23a395192ba3b5d2824ec9@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Enquiry Submitted on Rentfoxxy Website!', 919, '2026-07-11 12:28:16.310+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (627, '<a56ed7b2e3036f4ee78419fe406743bd@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Enquiry Submitted on Rentfoxxy Website!', 919, '2026-07-11 12:28:16.335+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (628, '<4a6fb1e6928c8eb06fb07742ab036b5b@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Enquiry Submitted on Rentfoxxy Website!', 919, '2026-07-11 12:28:16.356+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (629, '<6bb830db7ed279809d9080e2dd0fa4e6@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Enquiry Submitted on Rentfoxxy Website!', 919, '2026-07-11 12:28:16.388+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (630, '<c4a8b8ef0b006328c73f7054eb5f44e6@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Enquiry Submitted on Rentfoxxy Website!', 919, '2026-07-11 12:28:16.415+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (631, '<742f149b21d57ee07b04e0ef91da7402@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Enquiry Submitted on Rentfoxxy Website!', 919, '2026-07-11 12:28:16.460+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (632, '<6c807248a3226635b49bc0919ad54822@rentfoxxy.com>', '[Gmail]/Sent Mail', 'New Enquiry Submitted on Rentfoxxy Website!', 919, '2026-07-11 12:28:16.479+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;
INSERT INTO email_lead_ingestion_log (ingestion_id, message_id, mailbox, subject, lead_id, processed_at) VALUES (634, '<jKkpRE8ldImLACcY8dF2yAvKI6mTkbzOa9h0DkNEUg@rental.truetechservices.in>', '[Gmail]/Sent Mail', 'Corporate Rental Enquiry - TIDADS2024', 921, '2026-07-13 04:47:11.204+00'::timestamptz) ON CONFLICT (ingestion_id) DO NOTHING;

-- customers (2 rows)
INSERT INTO customers (customer_id, name, email, phone, gst_no, type, details, address, created_at, updated_at, status, company_name, pan_number, company_type, company_size, industry, billing_address, billing_city, billing_state, billing_pincode, shipping_same, shipping_address, shipping_city, shipping_state, shipping_pincode, whatsapp_number, designation, source_lead_stage, onboarded_by, onboarded_at, portal_enabled, notes, kyc_verified, kyc_verified_by, kyc_verified_at, source_lead_id, portal_password_hash, portal_last_login, kyc_status, kyc_documents) VALUES (291, 'ARPITA SHARMA', 'director@pawannirbhay.in', '6395219195', '07AAQCP1134P1ZX', 'Lead', '{"spock_person_name":"Arpita","spock_person_email":"director@pawannirbhay.in","spock_person_mobile":"6395219195","finance_contact_name":null,"finance_contact_email":null,"finance_contact_mobile":null}'::jsonb, 'Unknown, Unknown, Unknown', '2026-07-10 11:51:54.373+00'::timestamptz, '2026-07-10 12:01:52.903+00'::timestamptz, 1, 'pawannirbhay.in', NULL, '', NULL, '', 'F-14 , mansarovar park East ram Nagar, shahadara,delhi 110032', 'East Delhi', 'Delhi', '110032', TRUE, '', '', '', '', '', '', NULL, NULL, NULL, FALSE, '', FALSE, NULL, NULL, 916, NULL, NULL, 'pending', '[]'::jsonb) ON CONFLICT (customer_id) DO NOTHING;
INSERT INTO customers (customer_id, name, email, phone, gst_no, type, details, address, created_at, updated_at, status, company_name, pan_number, company_type, company_size, industry, billing_address, billing_city, billing_state, billing_pincode, shipping_same, shipping_address, shipping_city, shipping_state, shipping_pincode, whatsapp_number, designation, source_lead_stage, onboarded_by, onboarded_at, portal_enabled, notes, kyc_verified, kyc_verified_by, kyc_verified_at, source_lead_id, portal_password_hash, portal_last_login, kyc_status, kyc_documents) VALUES (292, 'RK NAIDU', 'batchmantechnologies@gmail.com', '7386558419', '37EUOPK3206G1ZJ', 'Lead', '{"spock_person_name":"RK NAIDU","spock_person_email":"batchmantechnologies@gmail.com","contact_person_name":"RK NAIDU","spock_person_mobile":"7386558419","contact_person_number":"7386558419"}'::jsonb, 'Unknown, Unknown, Unknown', '2026-07-11 13:26:01.742+00'::timestamptz, '2026-07-11 13:26:45.672+00'::timestamptz, 1, 'BATCHMAN TECHNOLOGIES', NULL, 'Pvt Ltd', NULL, '', 'Building No/ D NO : 46-18-11/2, FLAT NO 1, FIRST FLOOR,Name Of Building:PRASANTHI NILAYAM, PLOT NO 12, Road/Street: MANDAVARIPETA, DONDAPARTHI', 'Visakhapatnam ', 'Andhra Pradesh', '530016', TRUE, 'Building No/ D NO : 46-18-11/2, FLAT NO 1, FIRST FLOOR,Name Of Building:PRASANTHI NILAYAM, PLOT NO 12, Road/Street: MANDAVARIPETA, DONDAPARTHI', 'Visakhapatnam ', 'Andhra Pradesh', '530016', '', '', 'Deal', 1, '2026-07-11 13:26:45.672+00'::timestamptz, FALSE, NULL, FALSE, NULL, NULL, 920, NULL, NULL, 'pending', '[]'::jsonb) ON CONFLICT (customer_id) DO NOTHING;

-- customer_addresses (1 rows)
INSERT INTO customer_addresses (customer_address_id, customer_id, concern_person, mobile_no, address, pincode, is_head_office, source_lead_address_id, address_type, created_at, updated_at, city, state) VALUES (507, 291, 'ARPITA SHARMA', '6395219195', 'F-14 , mansarovar park East ram Nagar, shahadara,delhi 110032', '110032', TRUE, NULL, 'Shipping', '2026-07-10 11:51:54.377+00'::timestamptz, '2026-07-10 12:01:48.730+00'::timestamptz, 'East Delhi', 'Delhi') ON CONFLICT (customer_address_id) DO NOTHING;

-- Restore leads.customer_id after customers imported
UPDATE leads SET customer_id = 292 WHERE lead_id = 920;

-- Reset sequences
SELECT setval('public.leads_lead_id_seq', COALESCE((SELECT MAX(lead_id) FROM leads), 1), true);
SELECT setval('public.lead_addresses_address_id_seq', COALESCE((SELECT MAX(address_id) FROM lead_addresses), 1), true);
SELECT setval('public.lead_activities_activity_id_seq', COALESCE((SELECT MAX(activity_id) FROM lead_activities), 1), true);
SELECT setval('public.lead_remarks_remark_id_seq', COALESCE((SELECT MAX(remark_id) FROM lead_remarks), 1), true);
SELECT setval('public.lead_assignments_assignment_id_seq', COALESCE((SELECT MAX(assignment_id) FROM lead_assignments), 1), true);
SELECT setval('public.lead_followup_notifications_notification_id_seq', COALESCE((SELECT MAX(notification_id) FROM lead_followup_notifications), 1), true);
SELECT setval('public.lead_company_research_research_id_seq', COALESCE((SELECT MAX(research_id) FROM lead_company_research), 1), true);
SELECT setval('public.lead_orders_lead_order_id_seq', COALESCE((SELECT MAX(lead_order_id) FROM lead_orders), 1), true);
SELECT setval('public.email_lead_ingestion_log_ingestion_id_seq', COALESCE((SELECT MAX(ingestion_id) FROM email_lead_ingestion_log), 1), true);
SELECT setval('public.customers_customer_id_seq', COALESCE((SELECT MAX(customer_id) FROM customers), 1), true);
SELECT setval('public.customer_addresses_customer_address_id_seq', COALESCE((SELECT MAX(customer_address_id) FROM customer_addresses), 1), true);
SELECT setval('public.customer_documents_doc_id_seq', COALESCE((SELECT MAX(doc_id) FROM customer_documents), 1), true);
SELECT setval('public.email_queue_email_id_seq', COALESCE((SELECT MAX(email_id) FROM email_queue), 1), true);
SELECT setval('public.sales_quotations_id_seq', COALESCE((SELECT MAX(id) FROM sales_quotations), 1), true);

SET session_replication_role = DEFAULT;
COMMIT;