-- 360: permission_sections becomes the single, complete catalogue (Control, 27 Sep 2026).
--
-- 1. Two new columns: section_group (matrix group key, see
--    backend/constants/permissionCatalog.js SECTION_GROUPS) and hidden (kept, but
--    not rendered in the matrix by default: enforced nowhere in the code, or a
--    legacy umbrella reached only through an alias).
-- 2. Every section the code enforces gets a catalogue row (hidden ones are not
--    inserted, only marked where they already exist). Missing on live:
--    delivery_my_deliveries, delivery_technicians (on-disk 183 inserts them but
--    the live table lacks them; their role rows exist). INSERT ... ON CONFLICT
--    DO NOTHING — an existing row's description / sort_order is never changed.
-- 3. Group + hidden are filled only where section_group IS NULL, so a later
--    manual change is not overwritten by a re-run.
--
-- Nothing here touches role_permissions or user_permissions. Nothing is deleted.
-- Idempotent. Not replayed at boot.

ALTER TABLE public.permission_sections
  ADD COLUMN IF NOT EXISTS section_group VARCHAR(64);
ALTER TABLE public.permission_sections
  ADD COLUMN IF NOT EXISTS hidden BOOLEAN NOT NULL DEFAULT false;

INSERT INTO public.permission_sections (section, description, sort_order)
VALUES
  ('dashboard', 'Dashboard', 400),
  ('taskflow', 'TaskFlow', 401),
  ('leads', 'Leads', 402),
  ('lead_assignee_change', 'Lead Assignee Change (Sales team)', 403),
  ('lead_follow_ups', 'Follow-ups', 404),
  ('follow_ups', 'Follow-ups (list scope)', 405),
  ('lead_conversion', 'Lead Conversion', 406),
  ('lead_orders', 'Lead Orders', 407),
  ('customers', 'Customers', 408),
  ('customer_management', 'Customer Management', 409),
  ('customer_documents', 'Customer Documents', 410),
  ('kyc_management', 'KYC', 411),
  ('demo_management', 'Demos', 412),
  ('sales_quotations', 'Quotations', 413),
  ('sales_orders_sale', 'Sales Order – Sale', 414),
  ('sales_orders_rental', 'Sales Order – Rental', 415),
  ('sales_orders_replacement', 'Sales Orders – Replacement', 416),
  ('replacement_so_laptop_qc', 'Replacement SO — Laptop & QC', 417),
  ('so_laptop_qc', 'Sales SO — Laptops & QC (Rental/Sale)', 418),
  ('so_line_rate_config_edit', 'Sales SO — Edit line rate / config', 419),
  ('sales_order_cancel', 'Sales Order — Partial cancel (Rental/Sale)', 420),
  ('delivery_challans', 'Delivery Challans', 421),
  ('bluedart_awb_tracking', 'BlueDart AWB Tracking', 422),
  ('return_dc', 'Return DC', 423),
  ('delivery_register_management', 'Delivery Register', 424),
  ('delivery_register_otp', 'Delivery Register — View OTP', 425),
  ('technician_bucket', 'Delivery Technician', 426),
  ('delivery_technicians', 'Delivery Technicians', 427),
  ('delivery_my_deliveries', 'My Deliveries', 428),
  ('technicians_bucket_list', 'Technicians Bucket (Admin)', 429),
  ('payment_records', 'Payment Records', 430),
  ('vendor_management', 'Vendor Management', 431),
  ('vendor_repair_dc', 'Vendor Repair DC (Laptops)', 432),
  ('vendor_repair_dc_dispatch', 'Vendor Repair DC — Sign, Dispatch & Delivery', 433),
  ('vendor_return_to_vendor', 'Return to Vendor', 434),
  ('vendor_return_ticket', 'Vendor Return Tickets', 435),
  ('procurement', 'Procurement', 436),
  ('sales_pipeline', 'Sales Pipeline', 437),
  ('inventory_master_data', 'Master Data Dashboard', 438),
  ('inventory_vendor_master_data', 'Master Vendor Data', 439),
  ('inventory_return_master_data', 'Master Return Data', 440),
  ('floor_pipeline', 'Floor Pipeline', 441),
  ('floor_tickets', 'Floor Tickets', 442),
  ('floor_ticket_config_edit', 'Floor Tickets — Edit Config', 443),
  ('chip_level_repair', 'Chip Level Repair', 444),
  ('qc_management', 'QC Management', 445),
  ('dispatch_qc', 'Dispatch QC', 446),
  ('dispatch_charger', 'Dispatch QC — attach charger', 447),
  ('pending_inventory', 'QC Ready', 448),
  ('diagnosis_failed', 'Diagnosis Failed — Out for Repair', 449),
  ('tickets', 'Tickets (Legacy)', 450),
  ('inventory', 'Inventory', 451),
  ('inventory_management', 'Inventory Management', 452),
  ('inventory_asset_movement', 'Inventory — Asset Movement', 453),
  ('qc_move_to_ticket', 'QC Pending / Dead — move to QC Process + ticket', 454),
  ('qc_create_production_ticket', 'QC Process — Create Production Ticket', 455),
  ('ready_to_rent_location', 'Ready to Rent/Sell — change location', 456),
  ('customer_inventory', 'Customer Inventory', 457),
  ('customer_assets', 'Customer Assets (edit rate / export)', 458),
  ('ttspl_history', 'TTSPL History', 459),
  ('parts_dashboard', 'Parts Dashboard', 460),
  ('parts_inventory', 'Parts Inventory', 461),
  ('parts_approval', 'Parts Approval', 462),
  ('dispatch_charger_warehouse', 'Warehouse — dispatch charger handover', 463),
  ('parts_approval_export', 'Parts Approval — Export CSV', 464),
  ('parts_history', 'Parts Movement History', 465),
  ('parts_procurement', 'Spare Parts PO', 466),
  ('part_vendor_repair', 'Part Vendor Repair DC', 467),
  ('parts_discarded', 'Discarded Parts', 468),
  ('physical_dead_parts', 'Dead / Physical Parts', 469),
  ('scrap_challans', 'Scrap Challans', 470),
  ('scrap_approval', 'Approve Laptop Scrap', 471),
  ('parts_detach', 'Part Detach (Attached → Inventory)', 472),
  ('parts_requests', 'Part Requests (Floor)', 473),
  ('support_part_challan', 'Support Part Queue', 474),
  ('support_part_requests', 'Technician Parts Bucket', 475),
  ('parts', 'Parts (Legacy)', 476),
  ('guard_gate_checking', 'Guard Scanner', 477),
  ('gate_dashboard', 'Gate Dashboard', 478),
  ('warehouse', 'Warehouse', 479),
  ('dispatch', 'Dispatch', 480),
  ('dispatch_ops', 'Dispatch Operations', 481),
  ('dispatch_workflow', 'Dispatch Workflow', 482),
  ('dispatch_pending_orders', 'Dispatch Pending Orders', 483),
  ('customer_billing', 'Customer Billing', 484),
  ('vendor_billing_mgmt', 'Vendor Billing', 485),
  ('credit_notes', 'Credit Notes', 486),
  ('debit_notes', 'Debit Notes', 487),
  ('security_deposits', 'Security Deposits', 488),
  ('billing_dashboard', 'Billing Dashboard', 489),
  ('einvoice_ewb', 'E-Invoice & E-Way Bill', 490),
  ('dc_eway_bill', 'DC E-Way Bill Management', 491),
  ('sale_in_place', 'Lost / Buyout Sale (stop rent + sale order)', 492),
  ('support_tickets', 'Support Tickets', 493),
  ('support_requests', 'Support Requests (QR)', 494),
  ('support_settings', 'Support Settings', 495),
  ('support_technician', 'Support Technician (Field)', 496),
  ('analytics_dashboard', 'Analytics Dashboards (Manager & Sales)', 497),
  ('report_revenue', 'Report — Revenue', 498),
  ('report_inventory', 'Report — Inventory Utilisation', 499),
  ('report_lead_conversion', 'Report — Lead Conversion', 500),
  ('report_salesperson', 'Report — Salesperson', 501),
  ('report_collections', 'Report — Collections', 502),
  ('report_vendor_spend', 'Report — Vendor Spend', 503),
  ('report_laptop', 'Report — Technician / Laptop', 504),
  ('report_warehouse_laptops', 'Report — Warehouse Laptops', 505),
  ('report_sales_order', 'Report — Sales Order', 506),
  ('report_support_daily', 'Report — Daily Support Summary', 507),
  ('report_inward_outward', 'Report — Inward & Outward Summary', 508),
  ('production_qc_report', 'Report — Production QC', 509),
  ('reports_export', 'Export Reports', 510),
  ('users', 'User Management', 511),
  ('teams', 'Team Management', 512),
  ('roles', 'Role Management', 513),
  ('role_permissions', 'Role Permissions', 514),
  ('user_permissions', 'User Permissions', 515),
  ('company_settings', 'Company Settings', 516),
  ('asset_configuration', 'Asset Configuration', 517)
ON CONFLICT (section) DO NOTHING;

UPDATE public.permission_sections ps
   SET section_group = v.grp,
       hidden = v.hidden
  FROM (VALUES
  ('dashboard', 'core', false),
  ('taskflow', 'core', false),
  ('leads', 'sales', false),
  ('lead_assignee_change', 'sales', false),
  ('lead_follow_ups', 'sales', false),
  ('follow_ups', 'sales', false),
  ('lead_conversion', 'sales', false),
  ('lead_orders', 'sales', false),
  ('customers', 'sales', false),
  ('customer_management', 'sales', false),
  ('customer_documents', 'sales', false),
  ('kyc_management', 'sales', false),
  ('demo_management', 'sales', false),
  ('sales_quotations', 'sales', false),
  ('sales_orders_sale', 'sales', false),
  ('sales_orders_rental', 'sales', false),
  ('sales_orders_replacement', 'sales', false),
  ('replacement_so_laptop_qc', 'sales', false),
  ('so_laptop_qc', 'sales', false),
  ('so_line_rate_config_edit', 'sales', false),
  ('sales_order_cancel', 'sales', false),
  ('delivery_challans', 'sales', false),
  ('bluedart_awb_tracking', 'sales', false),
  ('return_dc', 'sales', false),
  ('delivery_register_management', 'sales', false),
  ('delivery_register_otp', 'sales', false),
  ('technician_bucket', 'sales', false),
  ('delivery_technicians', 'sales', false),
  ('delivery_my_deliveries', 'sales', false),
  ('technicians_bucket_list', 'sales', false),
  ('payment_records', 'sales', false),
  ('vendor_management', 'vendor', false),
  ('vendor_repair_dc', 'vendor', false),
  ('vendor_repair_dc_dispatch', 'vendor', false),
  ('vendor_return_to_vendor', 'vendor', false),
  ('vendor_return_ticket', 'vendor', false),
  ('procurement', 'vendor', false),
  ('sales_pipeline', 'vendor', false),
  ('inventory_master_data', 'master', false),
  ('inventory_vendor_master_data', 'master', false),
  ('inventory_return_master_data', 'master', false),
  ('floor_pipeline', 'floor', false),
  ('floor_tickets', 'floor', false),
  ('floor_ticket_config_edit', 'floor', false),
  ('chip_level_repair', 'floor', false),
  ('qc_management', 'floor', false),
  ('dispatch_qc', 'floor', false),
  ('dispatch_charger', 'floor', false),
  ('pending_inventory', 'floor', false),
  ('diagnosis_failed', 'floor', false),
  ('tickets', 'floor', false),
  ('inventory', 'inventory', false),
  ('inventory_management', 'inventory', false),
  ('inventory_asset_movement', 'inventory', false),
  ('qc_move_to_ticket', 'inventory', false),
  ('qc_create_production_ticket', 'inventory', false),
  ('ready_to_rent_location', 'inventory', false),
  ('customer_inventory', 'inventory', false),
  ('customer_assets', 'inventory', false),
  ('ttspl_history', 'inventory', false),
  ('parts_dashboard', 'parts', false),
  ('parts_inventory', 'parts', false),
  ('parts_approval', 'parts', false),
  ('dispatch_charger_warehouse', 'parts', false),
  ('parts_approval_export', 'parts', false),
  ('parts_history', 'parts', false),
  ('parts_procurement', 'parts', false),
  ('part_vendor_repair', 'parts', false),
  ('parts_discarded', 'parts', false),
  ('physical_dead_parts', 'parts', false),
  ('scrap_challans', 'parts', false),
  ('scrap_approval', 'parts', false),
  ('parts_detach', 'parts', false),
  ('parts_requests', 'parts', false),
  ('support_part_challan', 'parts', false),
  ('support_part_requests', 'parts', false),
  ('parts', 'parts', false),
  ('guard_gate_checking', 'gate', false),
  ('gate_dashboard', 'gate', false),
  ('warehouse', 'dispatch', false),
  ('dispatch', 'dispatch', false),
  ('dispatch_ops', 'dispatch', false),
  ('dispatch_workflow', 'dispatch', false),
  ('dispatch_pending_orders', 'dispatch', false),
  ('customer_billing', 'finance', false),
  ('vendor_billing_mgmt', 'finance', false),
  ('credit_notes', 'finance', false),
  ('debit_notes', 'finance', false),
  ('security_deposits', 'finance', false),
  ('billing_dashboard', 'finance', false),
  ('einvoice_ewb', 'finance', false),
  ('dc_eway_bill', 'finance', false),
  ('sale_in_place', 'finance', false),
  ('support_tickets', 'support', false),
  ('support_requests', 'support', false),
  ('support_settings', 'support', false),
  ('support_technician', 'support', false),
  ('analytics_dashboard', 'reports', false),
  ('report_revenue', 'reports', false),
  ('report_inventory', 'reports', false),
  ('report_lead_conversion', 'reports', false),
  ('report_salesperson', 'reports', false),
  ('report_collections', 'reports', false),
  ('report_vendor_spend', 'reports', false),
  ('report_laptop', 'reports', false),
  ('report_warehouse_laptops', 'reports', false),
  ('report_sales_order', 'reports', false),
  ('report_support_daily', 'reports', false),
  ('report_inward_outward', 'reports', false),
  ('production_qc_report', 'reports', false),
  ('reports_export', 'reports', false),
  ('users', 'admin', false),
  ('teams', 'admin', false),
  ('roles', 'admin', false),
  ('role_permissions', 'admin', false),
  ('user_permissions', 'admin', false),
  ('company_settings', 'admin', false),
  ('asset_configuration', 'admin', false),
  ('sales_orders', '_hidden', true),
  ('sales_orders_doc', '_hidden', true),
  ('reports', '_hidden', true),
  ('reports_access', '_hidden', true),
  ('manager_dashboard', '_hidden', true),
  ('catalogue', '_hidden', true),
  ('invoices', '_hidden', true),
  ('orders', '_hidden', true),
  ('permissions', '_hidden', true),
  ('operation_management', '_hidden', true),
  ('parts_pricing', '_hidden', true),
  ('qc_add_laptop', '_hidden', true),
  ('support_dashboard', '_hidden', true),
  ('support_triage', '_hidden', true),
  ('support_work_orders', '_hidden', true),
  ('support_pickup_repair', '_hidden', true),
  ('support_pickup_return', '_hidden', true),
  ('support_replacement', '_hidden', true),
  ('support_field_visit', '_hidden', true),
  ('support_parts_request', '_hidden', true),
  ('support_parts_approve', '_hidden', true),
  ('support_charges', '_hidden', true),
  ('support_approvals', '_hidden', true),
  ('support_dispatch', '_hidden', true),
  ('support_bucket', '_hidden', true),
  ('support_groups', '_hidden', true),
  ('support_customer_portal', '_hidden', true),
  ('support_reports', '_hidden', true),
  ('support_sla_admin', '_hidden', true),
  ('support_taxonomy', '_hidden', true),
  ('support_charges_billing', '_hidden', true),
  ('support_warehouse_receipt', '_hidden', true)
  ) AS v(section, grp, hidden)
 WHERE ps.section = v.section
   AND ps.section_group IS NULL;

CREATE INDEX IF NOT EXISTS idx_permission_sections_group
  ON public.permission_sections (section_group, sort_order);
