FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --only=production

# Copy app
COPY . .

# Prisma
RUN npx prisma generate

EXPOSE 5001

CMD ["node", "server.js"]
