/** Canonical application permission section keys */
export const APPLICATION_SECTIONS = [
  'dashboard',
  'analytics_dashboard',
  'leads',
  'lead_follow_ups',
  'lead_conversion',
  'customers',
  'customer_documents',
  'sales_quotations',
  'sales_orders_doc',
  'sales_orders_sale',
  'sales_orders_rental',
  'sales_orders_replacement',
  'replacement_so_laptop_qc',
  'so_laptop_qc',
  'sales_order_cancel',
  'delivery_challans',
  'return_dc',
  'delivery_register_management',
  'delivery_register_otp',
  'technician_bucket',
  'delivery_technicians',
  'delivery_my_deliveries',
  'support_technician',
  'technicians_bucket_list',
  'payment_records',
  'vendor_management',
  'procurement',
  'sales_pipeline',
  'floor_pipeline',
  'floor_tickets',
  'floor_ticket_config_edit',
  'chip_level_repair',
  'qc_management',
  'dispatch_qc',
  'pending_inventory',
  'tickets',
  'inventory',
  'inventory_management',
  'inventory_asset_movement',
  'parts',
  'parts_inventory',
  'customer_inventory',
  'ttspl_history',
  'warehouse',
  'dispatch',
  'dispatch_ops',
  'dispatch_workflow',
  'dispatch_pending_orders',
  'customer_billing',
  'vendor_billing_mgmt',
  'credit_notes',
  'debit_notes',
  'security_deposits',
  'billing_dashboard',
  'einvoice_ewb',
  'support_tickets',
  'support_settings',
  'reports',
  'reports_access',
  'reports_export',
  'manager_dashboard',
  'users',
  'teams',
  'roles',
  'role_permissions',
  'user_permissions',
  'company_settings',
  'asset_configuration',
];

export const SECTION_LABELS = {
  dashboard: 'Dashboard',
  analytics_dashboard: 'Analytics Dashboard',
  leads: 'Leads',
  lead_follow_ups: 'Follow-ups',
  lead_conversion: 'Lead Conversion',
  customers: 'Customers',
  customer_documents: 'Customer Documents',
  sales_quotations: 'Quotations',
  sales_orders_doc: 'Sales Orders (legacy)',
  sales_orders_sale: 'Sales Order – Sale',
  sales_orders_rental: 'Sales Order – Rental',
  sales_orders_replacement: 'Sales Orders – Replacement',
  replacement_so_laptop_qc: 'Replacement SO — Laptop & QC',
  so_laptop_qc: 'Sales SO — Laptops & QC (Rental/Sale)',
  sales_order_cancel: 'Sales Order — Partial cancel (Rental/Sale)',
  delivery_challans: 'Delivery Challans',
  return_dc: 'Return DC',
  delivery_register_management: 'Delivery Register',
  delivery_register_otp: 'Delivery Register — View OTP',
  technician_bucket: 'Delivery Technician',
  delivery_technicians: 'Delivery Technicians',
  delivery_my_deliveries: 'My Deliveries',
  support_technician: 'Support Technician (Field)',
  technicians_bucket_list: 'Technicians Bucket (Admin)',
  payment_records: 'Payment Records',
  vendor_management: 'Vendor Management',
  procurement: 'Procurement',
  sales_pipeline: 'Sales Pipeline',
  floor_pipeline: 'Floor Pipeline',
  floor_tickets: 'Floor Tickets',
  floor_ticket_config_edit: 'Floor Tickets — Edit Config',
  chip_level_repair: 'Chip Level Repair',
  qc_management: 'QC Management',
  dispatch_qc: 'Dispatch QC',
  pending_inventory: 'QC Ready',
  tickets: 'Tickets (Legacy)',
  inventory: 'Inventory',
  inventory_management: 'Inventory Management',
  inventory_asset_movement: 'Inventory — Asset Movement',
  parts: 'Parts (Legacy)',
  parts_inventory: 'Parts Inventory',
  customer_inventory: 'Customer Inventory',
  dispatch_workflow: 'Dispatch Workflow',
  dispatch_pending_orders: 'Dispatch Pending Orders',
  ttspl_history: 'TTSPL History',
  warehouse: 'Warehouse',
  dispatch: 'Dispatch',
  dispatch_ops: 'Dispatch Operations',
  customer_billing: 'Customer Billing',
  vendor_billing_mgmt: 'Vendor Billing',
  credit_notes: 'Credit Notes',
  debit_notes: 'Debit Notes',
  security_deposits: 'Security Deposits',
  billing_dashboard: 'Billing Dashboard',
  einvoice_ewb: 'E-Invoice & E-Way Bill',
  support_tickets: 'Support Tickets',
  support_settings: 'Support Settings',
  reports: 'Reports',
  reports_access: 'Reports Access',
  reports_export: 'Export Reports',
  manager_dashboard: 'Manager Dashboard',
  users: 'User Management',
  teams: 'Team Management',
  roles: 'Role Management',
  role_permissions: 'Role Permissions',
  user_permissions: 'User Permissions',
  company_settings: 'Company Settings',
  asset_configuration: 'Asset Configuration',
};

export const SECTION_GROUPS = {
  Core: ['dashboard', 'analytics_dashboard'],
  'Lead & Sales CRM': [
    'leads', 'lead_follow_ups', 'lead_conversion', 'customers', 'customer_documents',
    'sales_quotations', 'sales_orders_sale', 'sales_orders_rental', 'sales_orders_replacement',
    'replacement_so_laptop_qc', 'so_laptop_qc', 'sales_order_cancel', 'delivery_challans', 'return_dc',
    'delivery_register_management', 'delivery_register_otp', 'technician_bucket', 'delivery_technicians', 'delivery_my_deliveries', 'technicians_bucket_list', 'payment_records',
  ],
  'Vendor & Procurement': ['vendor_management', 'procurement', 'sales_pipeline'],
  'Floor & Quality': ['floor_pipeline', 'floor_tickets', 'floor_ticket_config_edit', 'chip_level_repair', 'qc_management', 'dispatch_qc', 'pending_inventory', 'tickets'],
  'Inventory & Parts': [
    'inventory', 'inventory_management', 'inventory_asset_movement', 'parts', 'parts_inventory', 'customer_inventory', 'ttspl_history',
  ],
  'Warehouse & Dispatch': ['warehouse', 'dispatch', 'dispatch_ops', 'dispatch_workflow', 'dispatch_pending_orders'],
  'Finance & Billing': [
    'customer_billing', 'vendor_billing_mgmt', 'credit_notes', 'debit_notes',
    'security_deposits', 'billing_dashboard', 'einvoice_ewb',
  ],
  Support: ['support_tickets', 'support_settings', 'support_technician'],
  'Reports & Analytics': ['reports', 'reports_access', 'reports_export', 'manager_dashboard'],
  'Settings & Admin': ['users', 'teams', 'roles', 'role_permissions', 'user_permissions', 'company_settings', 'asset_configuration'],
};

export const GROUP_COLORS = {
  Core: 'text-gray-600 border-gray-200',
  'Lead & Sales CRM': 'text-blue-600 border-blue-200',
  'Vendor & Procurement': 'text-emerald-600 border-emerald-200',
  'Floor & Quality': 'text-indigo-600 border-indigo-200',
  'Inventory & Parts': 'text-teal-600 border-teal-200',
  'Warehouse & Dispatch': 'text-sky-600 border-sky-200',
  'Finance & Billing': 'text-amber-600 border-amber-200',
  Support: 'text-pink-600 border-pink-200',
  'Reports & Analytics': 'text-violet-600 border-violet-200',
  'Settings & Admin': 'text-slate-600 border-slate-200',
};

export const PERMISSION_ACTIONS = ['can_view', 'can_create', 'can_edit', 'can_delete'];

/** Legacy umbrella keys — kept in DB for backward compat but hidden from role-permission UI. */
export const HIDDEN_ROLE_PERMISSION_SECTIONS = new Set([
  'sales_orders',
  'sales_orders_doc',
]);

export function isHiddenRolePermissionSection(section) {
  return HIDDEN_ROLE_PERMISSION_SECTIONS.has(section);
}

export function visibleRolePermissionSections(sections) {
  return (sections || []).filter((s) => !isHiddenRolePermissionSection(s));
}

export const ACTION_ALIASES = {
  view: 'can_view',
  create: 'can_create',
  edit: 'can_edit',
  delete: 'can_delete',
};

export function normalizeAction(action) {
  if (!action) return null;
  const key = String(action).trim();
  if (PERMISSION_ACTIONS.includes(key)) return key;
  return ACTION_ALIASES[key] || null;
}
